services:
  flash-recon:
    container_name: flash-recon-${USER}
    image: flash-recon:latest
    build:
      context: .
    working_dir: /workspace
    command: ["tail", "-f","/dev/null"]
    gpus: all
    ports:
      - "${HOST_PORT_1:-9090}:9090"
      - "${HOST_PORT_2:-9876}:9876"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/workspace
      - uv-cache:/root/.cache/uv
    tty: true
    stdin_open: true

volumes:
  uv-cache:
    external: true