services:
  flash-recon:
    container_name: flash-recon
    build:
      context: .
    working_dir: /workspace
    command: ["tail", "-f","/dev/null"]
    gpus: all
    devices:
      - /dev/v4l/by-id/usb-Global_Shutter_Camera_Global_Shutter_Camera_01.00.00-video-index0:/dev/mapping-cam
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
