[project]
name = "flash-recon"
version = "0.1.0"
description = "Accelerating video odometry"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "torch",
    "torchvision",
    "opencv-python",
]

[tool.uv.sources]
torch = { index = "torch-cuda" }
torchvision = { index = "torch-cuda" }

[[tool.uv.index]]
name = "torch-cuda"
url = "https://download.pytorch.org/whl/cu128"

[tool.uv.extra-build-dependencies]
lietorch = ["torch"]
torch-scatter = ["torch"]
geometry = ["torch"]
neural = ["torch"]

[project.optional-dependencies]
droid-slam = [
    "torch-scatter",
    "lietorch @ git+https://github.com/princeton-vl/lietorch.git",
]

flash-recon = [
    "geometry @ /workspace/geometry",
    "neural @ /workspace/neural",
    "visionrt @ https://github.com/abiel-almonte/visionrt/releases/download/v1.0.0/visionrt-0.1.0-cp313-cp313-linux_x86_64.whl",
]

[dependency-groups]
dev = [
    "black",
    "pybind11",
    "pybind11-stubgen",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["flash_recon*"]
